# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "repvar"
version = "0.1.0"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
regex = "1"
dict = "0.1.5"
