# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "repvar"
version = "0.6.3"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
description = """
    A tiny CLI tool that replaces variables of the style `${KEY}`
    in text with their respective value.
    It can also be used as a rust library
    """
license = "GPL-3.0-or-later"
repository = "https://github.com/hoijui/repvar"
keywords = ["cli", "ci", "variable-replacement"]
categories = ["command-line-utilities", "text-processing"]
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["cargo", "derive"] }
# We can not yet use `dotenv` upstream, as long as this PR is unmerged:
# https://github.com/dotenv-rs/dotenv/pull/78
# Sadly, the project loks head-less (no active owners/maintainers),
# see this related issue:
# https://github.com/dotenv-rs/dotenv/issues/74
dotenv = { git = "https://github.com/hoijui/dotenv.git" }
lazy_static = "1.4"
regex = "1.6"
thiserror = "1.0"
typed-builder = "0.10"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
tempfile = "3.3"
