# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "repvar"
version = "0.9.0"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
description = """
    A tiny CLI tool that replaces variables of the style `${KEY}`
    in text with their respective value.
    It can also be used as a rust library
    """
license = "GPL-3.0-or-later"
repository = "https://github.com/hoijui/repvar"
keywords = ["cli", "ci", "variable-replacement"]
categories = ["command-line-utilities", "text-processing"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["cargo"] }
cli-utils = { version = "0.4", git = "https://github.com/hoijui/cli-utils-rs.git" }
const_format = "0.2"
# We can not yet use `dotenv` upstream, as long as this PR is unmerged:
# https://github.com/dotenv-rs/dotenv/pull/78
# Sadly, the project loks head-less (no active owners/maintainers),
# see this related issue:
# https://github.com/dotenv-rs/dotenv/issues/74
dotenv = { git = "https://github.com/hoijui/dotenv.git" }
git-version = "0.3"
lazy_static = "1.4"
regex = "1.6"
thiserror = "1.0"
typed-builder = "0.14"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.3"
